/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import dominio.Cliente;
import dominio.Restaurante;
import dominio.Sistema;
import dominio.Sorteo;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Guillermo
 */
public class VentanaRealizarSorteo extends javax.swing.JFrame {

    private JFrame padre;
    private Sistema sistema;

    //Constructor
    public VentanaRealizarSorteo(VentanaPrincipal ventanaPrincipal, Sistema sistema) {
        initComponents();
        this.padre = ventanaPrincipal;
        this.sistema = sistema;
        //carga el combobox de restaurantes con todos los restaurantes cargados en el sistema
        Restaurante[] restaurantes = new Restaurante[this.sistema.getRestaurantes().size()];
        for (int i = 0; i < restaurantes.length; i++) {
            restaurantes[i] = this.sistema.getRestaurantes().get(i);
        }
        cmbBxRestaurantes.setModel(new DefaultComboBoxModel(restaurantes));
        Restaurante restaurante = this.sistema.getRestaurantes().get(0);
        setCBSorteos(restaurante);
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblElegirRestaurante = new javax.swing.JLabel();
        btnRealizarSorteo = new javax.swing.JButton();
        lblCantGanadores = new javax.swing.JLabel();
        cmbBxRestaurantes = new javax.swing.JComboBox<String>();
        cmbBxSorteos = new javax.swing.JComboBox<String>();
        LblElegirRestaurante = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblTitulo.setText("REALIZAR SORTEO");

        lblElegirRestaurante.setText("Elegir que restaurante realiza el sorteo:");

        btnRealizarSorteo.setText("REALIZAR SORTEO");
        btnRealizarSorteo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarSorteoActionPerformed(evt);
            }
        });

        cmbBxRestaurantes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbBxRestaurantes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbBxRestaurantesFocusLost(evt);
            }
        });
        cmbBxRestaurantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBxRestaurantesActionPerformed(evt);
            }
        });

        cmbBxSorteos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Elija un Restaurant" }));
        cmbBxSorteos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmbBxSorteosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbBxSorteosFocusLost(evt);
            }
        });

        LblElegirRestaurante.setText("Elegir sorteo (si aparece en blanco no hay sorteos)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(btnRealizarSorteo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblElegirRestaurante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbBxRestaurantes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbBxSorteos, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(LblElegirRestaurante)))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblCantGanadores)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(38, 38, 38)
                .addComponent(lblElegirRestaurante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbBxRestaurantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(LblElegirRestaurante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbBxSorteos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btnRealizarSorteo)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 134, Short.MAX_VALUE)
                    .addComponent(lblCantGanadores)
                    .addGap(0, 134, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnRealizarSorteoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarSorteoActionPerformed
        //Se realiza el sorteo con el restaurante seleccion
        Sorteo sorteo = (Sorteo) cmbBxSorteos.getSelectedItem();
        if (sorteo != null) {
            if (!sorteo.getParticipantes().isEmpty()) {
                ArrayList<Cliente> ganadores = sorteo.realizarSorteo();
                if (!ganadores.isEmpty()) {
                    //hubo ganadores, mostrar su informacion
                    String output = "Ganador(es): \n";
                    for (int i = 0; i < ganadores.size(); i++) {
                        output = output + ganadores.get(i) + "\n";
                    }
                    JOptionPane.showMessageDialog(null, output);
                    this.dispose();
                    this.padre.setEnabled(true);
                    this.padre.setVisible(true);
                }
            } else {
                JOptionPane.showMessageDialog(null, "No hay clientes participantes del sorteo");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe elejir un sorteo");
        }
    }//GEN-LAST:event_btnRealizarSorteoActionPerformed

    private void cmbBxRestaurantesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbBxRestaurantesFocusLost

    }//GEN-LAST:event_cmbBxRestaurantesFocusLost

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.dispose();
        this.padre.setEnabled(true);
        this.padre.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void cmbBxSorteosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbBxSorteosFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBxSorteosFocusLost

    private void cmbBxSorteosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbBxSorteosFocusGained


    }//GEN-LAST:event_cmbBxSorteosFocusGained

    private void cmbBxRestaurantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBxRestaurantesActionPerformed
        // TODO add your handling code here:
        Restaurante restaurante = (Restaurante) cmbBxRestaurantes.getSelectedItem();
        setCBSorteos(restaurante);
    }//GEN-LAST:event_cmbBxRestaurantesActionPerformed

    private void setCBSorteos(Restaurante restaurante) {
        int cantSorteos = 0;
        for (int i = 0; i < restaurante.getSorteos().size(); i++) {
            if (!((Sorteo) restaurante.getSorteos().get(i)).isRealizado()) {
                cantSorteos++;
            }
        }
        Sorteo[] sorteos = new Sorteo[cantSorteos];
        cantSorteos = 0;
        for (int i = 0; i < restaurante.getSorteos().size(); i++) {
            Sorteo elSorteo = (Sorteo) restaurante.getSorteos().get(i);
            if (!elSorteo.isRealizado()) {
                sorteos[cantSorteos] = (Sorteo) restaurante.getSorteos().get(i);
                cantSorteos++;
            }
        }
        cmbBxSorteos.setModel(new DefaultComboBoxModel(sorteos));

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblElegirRestaurante;
    private javax.swing.JButton btnRealizarSorteo;
    private javax.swing.JComboBox<String> cmbBxRestaurantes;
    private javax.swing.JComboBox<String> cmbBxSorteos;
    private javax.swing.JLabel lblCantGanadores;
    private javax.swing.JLabel lblElegirRestaurante;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
